spring:
  profiles:
    active: development
  datasource:
    url: jdbc:h2:mem:applicationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jdbc-url: jdbc:h2:mem:applicationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    database-platform: org.hibernate.dialect.H2Dialect

spring.h2.console.enabled: true # http://localhost:8080/h2-console/

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  default-serialization-format: application/json
  datasource:
    url: jdbc:h2:mem:camundadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
server.port: 8081
spring.devtools:
  restart:
    enabled: false # Do not enable this with ObjectValues as variables!
camunda.bpm.job-execution:
  #   deployment-aware: true
  wait-time-in-millis: 5000
  max-wait: 10000


quotation:
  api_url: ${QUOTATION_SERVICE_URL:http://localhost:8085/api/travel-requests}

# application.properties
logging:
  level:
    root: info
    com.ntconsult: debug

aws:
  sns:
    topic-arn: ${SNS_TOPIC_ARN:arn:aws:sns:us-east-1:674642957453:MonorepoStack-NotificationTopicEB7A0DF1-fYtraN3k1LJv}

cloudwatch:
  accessKey: ${ACCESS_KEY_AWS:asdas}
  secretKey: ${SECRET_KEY_AWS:asda+Dv9c54nuBI2Hfgeqv0}


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui